#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

TARGET_REPO="skulldogged/gpui-ghostty-agent-terminal"
OWNER_LOGIN="skulldogged"
EXPECTED_TARGET_REPO="$TARGET_REPO"
EXPECTED_OWNER_LOGIN="$OWNER_LOGIN"
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
CONFIG_ROOT="${XDG_CONFIG_HOME:-${HOME:?HOME must be set}/.config}/codex-github-machine"
DATA_ROOT="${XDG_DATA_HOME:-$HOME/.local/share}/codex-github-machine"
BIN_ROOT="$HOME/.local/bin"
ENV_FILE="$CONFIG_ROOT/setup.env"
START_STAGE=1
WINDOWS_HOST=false
EXISTING_MACHINE_USER=""

case "$(uname -s 2>/dev/null || true)" in
  MINGW*|MSYS*|CYGWIN*) WINDOWS_HOST=true ;;
esac

usage() {
  printf 'Usage: %s [--from-stage 1-6] [--existing-machine-user USER]\n' "${0##*/}"
  printf 'Resume after completed work with, for example, --from-stage 4.\n'
  printf 'Skip account creation for an existing invited machine user with --existing-machine-user.\n'
}

while (( $# )); do
  case "$1" in
    --from-stage)
      shift
      [[ $# -gt 0 ]] || { usage >&2; exit 2; }
      START_STAGE=$1
      ;;
    --from-stage=*)
      START_STAGE=${1#--from-stage=}
      ;;
    --existing-machine-user)
      shift
      [[ $# -gt 0 ]] || { usage >&2; exit 2; }
      EXISTING_MACHINE_USER=$1
      ;;
    --existing-machine-user=*)
      EXISTING_MACHINE_USER=${1#--existing-machine-user=}
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown argument: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

if [[ ! "$START_STAGE" =~ ^[1-6]$ ]]; then
  printf 'Stage must be a number from 1 through 6.\n' >&2
  exit 2
fi

mkdir -p "$CONFIG_ROOT" "$DATA_ROOT" "$BIN_ROOT"
chmod 700 "$CONFIG_ROOT" "$DATA_ROOT"

if (( START_STAGE > 1 )); then
  if [[ ! -r "$ENV_FILE" ]]; then
    printf 'Cannot resume: setup state is missing: %s\n' "$ENV_FILE" >&2
    exit 1
  fi
  # The wizard writes only constrained public values to this file.
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  if [[ "${TARGET_REPO:-}" != "$EXPECTED_TARGET_REPO" || \
        "${OWNER_LOGIN:-}" != "$EXPECTED_OWNER_LOGIN" ]]; then
    printf 'Cannot resume: saved repository identity does not match this wizard.\n' >&2
    exit 1
  fi
  : "${AGENT_GITHUB_USER:?Cannot resume without AGENT_GITHUB_USER in $ENV_FILE}"
fi

_STAGE_INDEX=$((START_STAGE - 1))

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf 'Required command not found: %s\n' "$1" >&2
    exit 1
  fi
}

for dependency in gh git ssh ssh-keygen; do
  require_command "$dependency"
done

validate_username() {
  if [[ ! "$1" =~ ^[A-Za-z0-9]([A-Za-z0-9-]{0,37}[A-Za-z0-9])?$ ]]; then
    warn "that does not look like a valid GitHub username"
    return 1
  fi
  if [[ "${1,,}" == "${OWNER_LOGIN,,}" ]]; then
    warn "the machine account must be different from $OWNER_LOGIN"
    return 1
  fi
}

verify_machine_user_exists() {
  if ! gh api "users/$1" --silent >/dev/null 2>&1; then
    warn "GitHub cannot find @$1 yet"
    return 1
  fi
}

if [[ -n "$EXISTING_MACHINE_USER" ]]; then
  if (( START_STAGE != 1 )); then
    printf '%s\n' '--existing-machine-user cannot be combined with --from-stage.' >&2
    exit 2
  fi
  if ! validate_username "$EXISTING_MACHINE_USER" || \
     ! verify_machine_user_exists "$EXISTING_MACHINE_USER"; then
    printf 'The existing machine user is invalid or unavailable: %s\n' \
      "$EXISTING_MACHINE_USER" >&2
    exit 1
  fi
  AGENT_GITHUB_USER=$EXISTING_MACHINE_USER
  write_env TARGET_REPO "$TARGET_REPO"
  write_env OWNER_LOGIN "$OWNER_LOGIN"
  write_env AGENT_GITHUB_USER "$AGENT_GITHUB_USER"
  START_STAGE=3
  _STAGE_INDEX=2
fi

if (( START_STAGE > 1 )); then
  banner "GitHub machine-user setup · resume at stage $START_STAGE"
else
  banner "GitHub machine-user setup"
fi

if (( START_STAGE <= 1 )); then
stage "Create and secure the machine account"
say "A human must create the machine account; GitHub prohibits automated registration."
warn "Use a dedicated email. Do not paste its password or recovery codes into this wizard."
open_url "https://github.com/signup?source=login"
step "Create the account. A transparent name such as skulldogged-agent is ideal."
step "Set the profile bio to say that @skulldogged operates it for Codex automation."
pause "Press Enter after account creation is complete."
open_url "https://github.com/settings/security"
step "While signed in as the machine account, enable 2FA and save recovery codes securely."
step "Add at least one backup recovery method. GitHub Support cannot bypass lost 2FA."
pause "Press Enter after 2FA and recovery are configured."
while true; do
  ask AGENT_GITHUB_USER "Machine-account username:"
  if validate_username "$AGENT_GITHUB_USER" && verify_machine_user_exists "$AGENT_GITHUB_USER"; then
    break
  fi
  warn "Create the account first, or enter its exact username."
done
write_env TARGET_REPO "$TARGET_REPO"
write_env OWNER_LOGIN "$OWNER_LOGIN"
write_env AGENT_GITHUB_USER "$AGENT_GITHUB_USER"
fi

if (( START_STAGE <= 2 )); then
stage "Grant and accept repository access"
say "Your existing gh login remains unchanged; these are browser-only account actions."
open_url "https://github.com/$TARGET_REPO/settings/access"
step "As @$OWNER_LOGIN, open Collaborators, choose Add people, and invite @$AGENT_GITHUB_USER."
pause "Press Enter after sending the collaborator invitation."
open_url "https://github.com/notifications"
step "Switch the browser to @$AGENT_GITHUB_USER and accept the repository invitation."
pause "Press Enter after accepting the invitation."
if permission=$(gh api "repos/$TARGET_REPO/collaborators/$AGENT_GITHUB_USER/permission" --jq .permission 2>/dev/null); then
  say "GitHub reports machine-user repository permission: $permission"
else
  warn "Could not verify collaborator access with the current owner-authenticated gh session."
  if ! confirm "Continue and verify access again when the token is created?"; then
    exit 1
  fi
fi
fi

if (( START_STAGE <= 3 )); then
stage "Create authentication and signing keys"
say "The builder gets separate SSH keys for Git authentication and verified commit signing."
warn "The private keys are unattended credentials. They will be owner-readable and outside Git."
if ! confirm "Generate or reuse the dedicated builder keys now?"; then
  exit 1
fi
KEY_ROOT="$DATA_ROOT/$AGENT_GITHUB_USER/keys"
AUTH_KEY="$KEY_ROOT/github-auth-ed25519"
SIGNING_KEY="$KEY_ROOT/github-signing-ed25519"
mkdir -p "$KEY_ROOT"
chmod 700 "$KEY_ROOT"
if [[ ! -f "$AUTH_KEY" ]]; then
  ssh-keygen -q -t ed25519 -N "" \
    -C "$AGENT_GITHUB_USER Codex builder authentication" -f "$AUTH_KEY"
fi
if [[ ! -f "$SIGNING_KEY" ]]; then
  ssh-keygen -q -t ed25519 -N "" \
    -C "$AGENT_GITHUB_USER Codex builder signing" -f "$SIGNING_KEY"
fi
chmod 600 "$AUTH_KEY" "$SIGNING_KEY"
chmod 644 "$AUTH_KEY.pub" "$SIGNING_KEY.pub"
write_env AGENT_GITHUB_AUTH_KEY "$AUTH_KEY"
write_env AGENT_GITHUB_SIGNING_KEY "$SIGNING_KEY"
open_url "https://github.com/settings/ssh/new"
step "As @$AGENT_GITHUB_USER, title this key 'Codex builder authentication'."
step "Choose Authentication Key, then paste this public key:"
say "$(<"$AUTH_KEY.pub")"
pause "Press Enter after adding the authentication key."
open_url "https://github.com/settings/ssh/new"
step "Title this key 'Codex builder signing' and choose Signing Key."
step "Paste this public key:"
say "$(<"$SIGNING_KEY.pub")"
pause "Press Enter after adding the signing key."
SSH_RESULT=$(ssh -T \
  -i "$AUTH_KEY" \
  -o IdentitiesOnly=yes \
  -o StrictHostKeyChecking=accept-new \
  git@github.com 2>&1 || true)
if [[ "$SSH_RESULT" == *"Hi $AGENT_GITHUB_USER!"* ]]; then
  say "GitHub SSH authentication resolves to @$AGENT_GITHUB_USER."
else
  warn "SSH identity did not verify as @$AGENT_GITHUB_USER."
  note "$SSH_RESULT"
  exit 1
fi
fi

if (( START_STAGE <= 4 )); then
stage "Create and store the API token"
say "This public personal repository currently requires a classic public_repo PAT for a collaborator."
warn "Keep the account limited to intended automation repositories; classic PATs are not per-repository."
if [[ "$WINDOWS_HOST" == true ]]; then
  TOKEN_FILE="$DATA_ROOT/$AGENT_GITHUB_USER/github-token.xml"
else
  TOKEN_FILE="$DATA_ROOT/$AGENT_GITHUB_USER/github-token"
fi
TOKEN_STORE_SOURCE="$SCRIPT_DIR/github-machine-user/token-store"
if [[ ! -x "$TOKEN_STORE_SOURCE" ]]; then
  warn "Missing token-store helper: $TOKEN_STORE_SOURCE"
  exit 1
fi
write_env AGENT_GITHUB_TOKEN_FILE "$TOKEN_FILE"
open_url "https://github.com/settings/tokens/new?description=Codex%20builder%20machine%20user&scopes=public_repo"
step "As @$AGENT_GITHUB_USER, choose a short practical expiration (90 days is a good start)."
step "Confirm that only public_repo is selected, then generate and copy the token."
ask_secret AGENT_GITHUB_PAT "Paste the token (hidden):"
if [[ -z "$AGENT_GITHUB_PAT" ]]; then
  warn "A token is required."
  exit 1
fi
TOKEN_LOGIN=$(GH_TOKEN="$AGENT_GITHUB_PAT" gh api user --jq .login 2>/dev/null || true)
if [[ "$TOKEN_LOGIN" != "$AGENT_GITHUB_USER" ]]; then
  unset AGENT_GITHUB_PAT
  warn "The token does not authenticate as @$AGENT_GITHUB_USER."
  exit 1
fi
if ! GH_TOKEN="$AGENT_GITHUB_PAT" gh api "repos/$TARGET_REPO" --silent >/dev/null 2>&1; then
  unset AGENT_GITHUB_PAT
  warn "The token cannot access $TARGET_REPO; check the accepted invitation and public_repo scope."
  exit 1
fi
if [[ "$WINDOWS_HOST" == true ]]; then
  if ! printf '%s' "$AGENT_GITHUB_PAT" | "$TOKEN_STORE_SOURCE" store-windows-dpapi; then
    unset AGENT_GITHUB_PAT
    warn "Windows could not protect the token with current-user DPAPI."
    exit 1
  fi
  say "The token is encrypted with Windows DPAPI for the current user."
elif printf '%s' "$AGENT_GITHUB_PAT" | "$TOKEN_STORE_SOURCE" store-secret-service; then
  say "The token is stored in Secret Service, not a file or GitHub Actions secret."
else
  warn "No usable Secret Service is available in this headless session."
  warn "The fallback is an owner-only 0600 file outside the repository: $TOKEN_FILE"
  if ! confirm "Use the owner-only token-file fallback?"; then
    unset AGENT_GITHUB_PAT
    exit 1
  fi
  printf '%s' "$AGENT_GITHUB_PAT" | "$TOKEN_STORE_SOURCE" store-file
  say "Stored the token in an owner-only file outside the repository."
fi
unset AGENT_GITHUB_PAT
fi

if (( START_STAGE <= 5 )); then
stage "Install guarded local commands"
say "The wrappers isolate machine-user operations from your existing gh and Git identities."
open_url "https://github.com/settings/emails"
step "As @$AGENT_GITHUB_USER, copy the account's GitHub-provided noreply email."
ask AGENT_GITHUB_EMAIL "Machine-account noreply email:"
if [[ ! "$AGENT_GITHUB_EMAIL" =~ ^[^[:space:]@]+@[^[:space:]@]+$ ]]; then
  warn "That does not look like an email address."
  exit 1
fi
write_env AGENT_GITHUB_EMAIL "$AGENT_GITHUB_EMAIL"
AGENT_GH_SOURCE="$SCRIPT_DIR/github-machine-user/agent-gh"
AGENT_GIT_SOURCE="$SCRIPT_DIR/github-machine-user/agent-git"
TOKEN_STORE_SOURCE="$SCRIPT_DIR/github-machine-user/token-store"
for source_file in "$AGENT_GH_SOURCE" "$AGENT_GIT_SOURCE" "$TOKEN_STORE_SOURCE"; do
  if [[ ! -r "$source_file" ]]; then
    warn "Missing wrapper template: $source_file"
    exit 1
  fi
done
for destination in "$BIN_ROOT/agent-gh" "$BIN_ROOT/agent-git" "$BIN_ROOT/agent-token-store"; do
  if [[ -e "$destination" ]]; then
    warn "Existing command will be backed up before replacement: $destination"
    if ! confirm "Replace $destination?"; then
      exit 1
    fi
    cp -p "$destination" "$destination.backup.$(date +%Y%m%d%H%M%S)"
  fi
done
install -m 700 "$AGENT_GH_SOURCE" "$BIN_ROOT/agent-gh"
install -m 700 "$AGENT_GIT_SOURCE" "$BIN_ROOT/agent-git"
install -m 700 "$TOKEN_STORE_SOURCE" "$BIN_ROOT/agent-token-store"
if [[ "$WINDOWS_HOST" == true ]]; then
  for source_file in \
    "$SCRIPT_DIR/github-machine-user/agent-gh.cmd" \
    "$SCRIPT_DIR/github-machine-user/agent-git.cmd" \
    "$SCRIPT_DIR/github-machine-user/windows-token-store.ps1"; do
    if [[ ! -r "$source_file" ]]; then
      warn "Missing Windows wrapper file: $source_file"
      exit 1
    fi
  done
  install -m 700 "$SCRIPT_DIR/github-machine-user/agent-gh.cmd" "$BIN_ROOT/agent-gh.cmd"
  install -m 700 "$SCRIPT_DIR/github-machine-user/agent-git.cmd" "$BIN_ROOT/agent-git.cmd"
  install -m 600 \
    "$SCRIPT_DIR/github-machine-user/windows-token-store.ps1" \
    "$BIN_ROOT/windows-token-store.ps1"

  BIN_ROOT_WINDOWS=$(cygpath -w "$BIN_ROOT")
  AGENT_MACHINE_BIN="$BIN_ROOT_WINDOWS" powershell.exe -NoProfile -Command '
    $bin = $env:AGENT_MACHINE_BIN
    $userPath = [Environment]::GetEnvironmentVariable("Path", "User")
    $entries = @($userPath -split ";" | Where-Object { $_ })
    if ($entries -notcontains $bin) {
      $newPath = (@($entries) + $bin) -join ";"
      [Environment]::SetEnvironmentVariable("Path", $newPath, "User")
    }
  '
  say "Installed PowerShell command shims and added $BIN_ROOT_WINDOWS to the user PATH."
  note "Open a new PowerShell window before invoking agent-gh or agent-git there."
fi
say "Installed $BIN_ROOT/agent-gh, $BIN_ROOT/agent-git, and the token-store helper."
"$BIN_ROOT/agent-gh" register "$TARGET_REPO"
"$BIN_ROOT/agent-gh" identity
"$BIN_ROOT/agent-git" identity
if [[ ":$PATH:" != *":$BIN_ROOT:"* ]]; then
  warn "$BIN_ROOT is not on PATH in this shell; use the full paths or add it later."
fi
fi

if (( START_STAGE <= 6 )); then
stage "Verify attribution with a disposable draft PR"
say "This test creates one empty signed commit, one temporary branch, and one draft PR."
say "The draft body mentions @$OWNER_LOGIN once so you can confirm notification delivery."
if ! confirm "Create the disposable verification branch and draft PR now?"; then
  SKIPPED+=("disposable GitHub identity verification")
  finish
  exit 0
fi
VERIFY_ROOT=$(mktemp -d "${TMPDIR:-/tmp}/codex-github-verify.XXXXXX")
cleanup_verify_root() {
  case "$VERIFY_ROOT" in
    "${TMPDIR:-/tmp}"/codex-github-verify.*)
      rm -rf -- "$VERIFY_ROOT"
      ;;
  esac
}
trap cleanup_verify_root EXIT
git clone --quiet "https://github.com/$TARGET_REPO.git" "$VERIFY_ROOT/repository"
(
  cd "$VERIFY_ROOT/repository"
  VERIFY_BRANCH="agent/identity-verification-$(date +%Y%m%d%H%M%S)-$$"
  git switch --quiet -c "$VERIFY_BRANCH"
  "$BIN_ROOT/agent-git" commit --allow-empty -m "chore: verify agent GitHub identity"
  VERIFY_COMMIT=$(git rev-parse HEAD)
  "$BIN_ROOT/agent-git" push "HEAD:refs/heads/$VERIFY_BRANCH"
  PR_URL=$("$BIN_ROOT/agent-gh" pr create \
    --base main \
    --head "$VERIFY_BRANCH" \
    --draft \
    --title "chore: verify agent GitHub identity" \
    --body "Temporary identity verification for @$AGENT_GITHUB_USER. @$OWNER_LOGIN, please confirm that this mention produced one notification.")
  PR_AUTHOR=$("$BIN_ROOT/agent-gh" pr view "$PR_URL" --json author --jq .author.login)
  COMMIT_AUTHOR=$("$BIN_ROOT/agent-gh" api \
    "repos/$TARGET_REPO/commits/$VERIFY_COMMIT" --jq '.author.login // "unlinked"')
  COMMIT_VERIFIED=$("$BIN_ROOT/agent-gh" api \
    "repos/$TARGET_REPO/commits/$VERIFY_COMMIT" --jq .commit.verification.verified)
  say "Draft PR: $PR_URL"
  say "PR author: $PR_AUTHOR"
  say "Commit account: $COMMIT_AUTHOR"
  say "Commit signature verified: $COMMIT_VERIFIED"
  if [[ "$PR_AUTHOR" != "$AGENT_GITHUB_USER" || "$COMMIT_AUTHOR" != "$AGENT_GITHUB_USER" ]]; then
    warn "Attribution did not resolve to @$AGENT_GITHUB_USER; leave the test open for diagnosis."
    exit 1
  fi
  if confirm "Close the draft PR and delete its temporary branch now?"; then
    "$BIN_ROOT/agent-gh" pr close "$PR_URL"
    "$BIN_ROOT/agent-git" push --delete "$VERIFY_BRANCH"
    say "Removed the disposable draft PR branch; the closed PR remains in GitHub history."
  else
    warn "Left the draft PR and branch in place: $PR_URL"
  fi
)
fi

finish
